baseurl: http://propertycross.com
permalink: /:title
safe: true
lsi: false

debug: false

name: PropertyCross
description: Helping you select a cross-platform mobile framework
githuburl: http://github.com/colineberhardt/PropertyFinderCrossPlatform

platforms:
  android: Android
  ios: iOS
  windowsphone: Windows Phone

extensions:
  android: apk
  ios: ipa
  windowsphone: xap
